name: Backport to solana-v2.0-tmp

on:
  pull_request:
    branches: [tmp]

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Backport to v2.0
        uses: ./.github/actions/backport
        with:
          label: v2.0
          base_branch: solana-v2.0
