name: Main

on:
  push:
    branches: [main, solana-v1.18]
  pull_request:
    branches: [main, solana-v1.18]

env:
  NIGHTLY_TOOLCHAIN: nightly-2023-10-05
  SOLANA_VERSION: 1.18.18

jobs:
  rust_fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          components: rustfmt
      - name: Run format
        run: cargo +${{ env.NIGHTLY_TOOLCHAIN }} fmt --all -- --check

  rust_clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-clippy-
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          components: clippy
      - name: Run clippy
        run: cargo +${{ env.NIGHTLY_TOOLCHAIN }} clippy --all --all-features --tests -- --deny=warnings

  cargo_build_test:
    name: Cargo Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-sbf-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-sbf-
      - uses: metaplex-foundation/actions/install-solana@v1
        with:
          cache: true
          version: ${{ env.SOLANA_VERSION }}
      - name: Build test programs
        run: |
          cargo build-sbf --manifest-path test-programs/cpi-target/Cargo.toml
          cargo build-sbf --manifest-path test-programs/primary/Cargo.toml
      - name: Test
        run: cargo test --all-features
